// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*ori_shell_executorTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool          = (*ori_shell_executorTool)(nil)
	_ pluginapi.MetadataProvider       = (*ori_shell_executorTool)(nil)
	_ pluginapi.PluginCompatibility    = (*ori_shell_executorTool)(nil)
	_ pluginapi.InitializationProvider = (*ori_shell_executorTool)(nil)
)

// OriShellExecutorParams represents the parameters for this plugin
type OriShellExecutorParams struct {
	Command        string `json:"command"`         // The shell command to execute. Must match allowed patterns and not match blocked patterns.
	WorkingDir     string `json:"working_dir"`     // Working directory for command execution. Must be within allowed directories. Defaults to current agent's project root.
	TimeoutSeconds int    `json:"timeout_seconds"` // Command timeout in seconds (1-300). Defaults to 60.
	Shell          string `json:"shell"`           // Shell to use: sh, bash, zsh, powershell, cmd. Defaults to sh on Unix, cmd on Windows.
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *ori_shell_executorTool) Call(ctx context.Context, args string) (string, error) {
	var params OriShellExecutorParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.Command == "" {
		return "", fmt.Errorf("required field 'command' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
