name: ori-shell-executor
version: 0.0.5
description: Execute shell commands with safety controls. Supports command allowlists, blocklists, and timeouts.
tags: ["dev-tools", "system", "automation"]

license: MIT
repository: https://github.com/johnjallday/ori-shell-executor

maintainers:
  - name: Ori Agent Team
    email: noreply@ori-agent.dev

platforms:
  - os: darwin
    architectures: [amd64, arm64]
  - os: linux
    architectures: [amd64, arm64]
  - os: windows
    architectures: [amd64, arm64]

requirements:
  min_ori_version: "0.0.25"
  api_version: "v1"
  dependencies: []

config:
  variables:
    - key: timeout_seconds
      name: Command Timeout
      description: Maximum time in seconds for command execution (1-300)
      type: int
      required: false
      default_value: 60

    - key: default_working_dir
      name: Default Working Directory
      description: "Default working directory when none is provided in a tool call."
      type: string
      required: false
      default_value: ""
      placeholder: "/path/to/project"

    - key: allowed_patterns
      name: Allowed Command Patterns
      description: "Command patterns to allow (one per line). Use * as wildcard. Example: 'git *' allows all git commands."
      type: string
      required: false
      default_value: "git *\ngo *\nmake *\nnpm *\nls *\ncat *\necho *\npwd\nwhich *\nenv"
      placeholder: "git *\ngo *\nls *"

    - key: blocked_patterns
      name: Blocked Command Patterns
      description: "Command patterns to block (one per line). These are checked BEFORE allowed patterns. Use for dangerous commands."
      type: string
      required: false
      default_value: "rm -rf /*\nrm -rf ~/*\nsudo *\n> /dev/*\ncurl * | sh\ncurl * | bash\nchmod 777 *"
      placeholder: "sudo *\nrm -rf *"

    - key: allow_shell_metacharacters
      name: Allow Shell Metacharacters
      description: "Allow shell operators like ;, |, &&, >, <, $(...). Disabled by default to prevent command chaining."
      type: bool
      required: false
      default_value: false

tool_definition:
  description: "Execute shell/bash commands with safety controls. Commands are validated against allowlist/blocklist patterns before execution. Use for running scripts, git commands, build tools, etc."
  parameters:
    - name: command
      type: string
      description: "The shell command to execute. Must match allowed patterns and not match blocked patterns."
      required: true

    - name: working_dir
      type: string
      description: "Working directory for command execution. Defaults to configured default_working_dir or agent context."
      required: false

    - name: timeout_seconds
      type: integer
      description: "Command timeout in seconds (1-300). Defaults to 60."
      required: false
      min: 1
      max: 300

    - name: shell
      type: string
      description: "Shell to use: sh, bash, zsh, powershell, cmd. Defaults to sh on Unix, cmd on Windows."
      required: false
      enum: [sh, bash, zsh, powershell, cmd]
